name: Build for GitHub Pages

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  #
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

# defaults:
#   run:
#     shell: bash


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install aarch64-apple-darwin target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build with wasm-pack
        run: wasm-pack build --release --target web

      - name: Preare artifact
        run: |
          mkdir public 
          mv pkg public
          mv index.html public
          mv main.js public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # deploy: 
  #   environment: 
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps: 
  #     - name: Deploy to Github Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
  #

